# Generated by Django 4.1.3 on 2022-11-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='songs',
            name='plays',
            field=models.BigIntegerField(default=0),
        ),
    ]
