# Generated by Django 4.1.3 on 2022-11-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0003_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='bio',
            field=models.TextField(default='Bio goes here'),
        ),
        migrations.AddField(
            model_name='artists',
            name='img_url',
            field=models.URLField(default=None),
        ),
    ]
