# Generated by Django 4.1.3 on 2022-11-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0005_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
