# Generated by Django 4.1.3 on 2022-11-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0006_albums'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genres',
        ),
    ]
