# Generated by Django 4.1.3 on 2022-11-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0008_playlists_alter_albums_title_alter_artists_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
