# Generated by Django 4.1.3 on 2022-11-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0009_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='is_explicit',
            field=models.BooleanField(default=False),
        ),
    ]
