# Generated by Django 4.1.3 on 2022-11-16 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0012_songs_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='playlist_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jams.playlists'),
        ),
    ]
