# Generated by Django 4.1.3 on 2022-11-16 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0013_songs_playlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='manager_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jams.managers'),
        ),
    ]
