# Generated by Django 4.1.3 on 2022-11-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0014_artists_manager_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artists',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='album_id',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='artist_id',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='playlist_id',
        ),
    ]
