# Generated by Django 4.1.3 on 2022-11-16 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0015_remove_artists_manager_id_remove_songs_album_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumsSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jams.songs')),
            ],
        ),
    ]
