# Generated by Django 4.1.3 on 2022-11-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0016_albumssongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumssongs',
            name='album_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jams.albums'),
        ),
        migrations.AlterField(
            model_name='albumssongs',
            name='song_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jams.songs'),
        ),
    ]
