# Generated by Django 4.1.3 on 2022-11-16 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0018_artistssongs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistsSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jams.playlists')),
                ('song_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jams.songs')),
            ],
        ),
    ]
