# Generated by Django 4.1.3 on 2022-11-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0022_delete_artistsmanagers_delete_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='img_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
