# Generated by Django 4.1.3 on 2022-11-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0024_managers_artistsmanagers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumssongs',
            old_name='album_id',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='albumssongs',
            old_name='song_id',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='artistssongs',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='artistssongs',
            old_name='song_id',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='playlistssongs',
            old_name='playlist_id',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='playlistssongs',
            old_name='song_id',
            new_name='song',
        ),
    ]
